base/urls.py
from base.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', home, name="home"),
    path('brands/', brands, name="brands"),
    path('how-it-works/', howItWorks, name="howItWorks"),
    path('privacy-policy/', privacyPolicy, name="privacyPolicy"),
    path('contact-us/', contact, name="contact"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car/urls.py
from car.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'car'

urlpatterns = [
    path('', getCars, name="getCars"),
    path('car/<int:id>/', carDetails, name="carDetails"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pluto/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('cars/', include('car.urls')),
    path('users/', include('user.urls')),
    path('auth/', include('account.urls')),
    path('hotels/', include('hotel.urls')),
    path('planes/', include('plane.urls')),
    path('payment/', include('payment.urls')),
]

# Serve static and media files manually if DEBUG is False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

handler404 = 'base.views.custom_404_view'

templates/pages/brands.html
{% extends 'layouts/app.html' %}
{% block content %}

    <section class="dealer-ship-section layout-radius">
        <div class="boxcar-container">
            <div class="boxcar-title-three wow fadeInUp">
                <ul class="breadcrumb">
                    <li><a href="{% url 'base:home' %}">Home</a></li>
                    <li><span>Car Brands</span></li>
                </ul>
                <h2>Car Brands</h2>
                <span>
                    Showing {{ brands.start_index }} to {{ brands.end_index }} of {{ brands.paginator.count }} brands
                </span>
            </div>

            <!-- Search, sort, reset -->
            {% comment %} <form method="get" class="title-listing" style="margin-bottom: 20px;">
                <div class="box-ip-search">
                    <input type="text" name="q" placeholder="Search Brands eg. Audi" value="{{ query }}">
                </div>
                <div class="text-box v1 d-flex" style="margin-top: 15px;">
                    <div class="form_boxes v3" style="padding-right: 30px;">
                        <small>Sort by</small>
                        <div class="drop-menu">
                            <div class="select"><span>{{ sort_by|title }}</span><i class="fa fa-angle-down"></i></div>
                            <input type="hidden" name="sort" value="{{ sort_by }}">
                            <ul class="dropdown" style="display: none;">
                                <li data-value="latest">Newest</li>
                                <li data-value="oldest">Oldest</li>
                            </ul>
                        </div>
                    </div>
                    <div class="form_boxes v3">
                        <a href="{% url 'base:brands' %}">
                            <small>Reset Filter</small>
                            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 21 21">
                                <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1">
                                    <path d="M14.5 3.5c2.414 1.377 4 4.022 4 7a8 8 0 1 1-8-8" />
                                    <path d="M14.5 7.5v-4h4" />
                                </g>
                            </svg>
                        </a>
                    </div>
                    <button type="submit" class="d-none">Submit</button>
                </div>
            </form> {% endcomment %}

            <!-- Brands List -->
            <div class="row">
                {% for brand in brands %}
                    <div class="dealer-block col-lg-3 col-md-6 col-sm-12">
                        <div class="inner-box">
                            <div class="image-box">
                                <figure class="image">
                                    <a href="#" style="width: 174px; height: 174px; overflow: hidden;">
                                        {% if brand.thumbnail %}
                                            <img src="{{ brand.thumbnail.url }}" alt="{{ brand.name }}">
                                        {% else %}
                                            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVQfxEyRp184pVTen_MQe-LEqhLZxhWAWj9A&s" alt="{{ brand.name }}">
                                        {% endif %}
                                    </a>
                                </figure>
                            </div>
                            <div class="content-box">
                                <h6 class="title"><a href="#">{{ brand.name }}</a></h6>
                                <div class="text">Explore cars from {{ brand.name }}</div>
                                <a href="{% url 'car:getCars' %}?car_brand={{ brand.id }}" class="deal-btn">
                                    See Cars
                                </a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="col-12 text-center">
                        <p>No brands found.</p>
                    </div>
                {% endfor %}
            </div>

            <!-- Pagination -->
            {% if brands.has_other_pages %}
                <div class="pagination-sec">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">

                            <!-- Previous Button -->
                            <li class="page-item {% if not brands.has_previous %}disabled{% endif %}">
                                <a class="page-link" href="{% if brands.has_previous %}?{% if query %}q={{ query }}&{% endif %}{% if sort_by %}sort={{ sort_by }}&{% endif %}page={{ brands.previous_page_number }}{% else %}#{% endif %}" aria-label="Previous">
                                    <span aria-hidden="true">
                                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M2.57983 5.99989C2.57983 5.7849 2.66192 5.56987 2.82573 5.4059L7.98559 0.24617C8.31382 -0.0820565 8.84598 -0.0820565 9.17408 0.24617C9.50217 0.574263 9.50217 1.10632 9.17408 1.43457L4.60841 5.99989L9.17376 10.5654C9.50185 10.8935 9.50185 11.4256 9.17376 11.7537C8.84566 12.0821 8.31366 12.0821 7.98544 11.7537L2.82555 6.59404C2.66176 6.42999 2.57983 6.21495 2.57983 5.99989Z" fill="#050B20"/>
                                        </svg>
                                    </span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>

                            <!-- Page Numbers -->
                            {% for num in brands.paginator.page_range %}
                                {% if num == brands.number %}
                                    <li class="page-item"><a class="page-link" href="#" style="border: 1px solid #050B20;">{{ num }}</a></li>
                                {% elif num <= brands.number|add:'2' and num >= brands.number|add:'-2' %}
                                    <li class="page-item"><a class="page-link" href="?{% if query %}q={{ query }}&{% endif %}{% if sort_by %}sort={{ sort_by }}&{% endif %}page={{ num }}">{{ num }}</a></li>
                                {% elif num == 1 or num == brands.paginator.num_pages %}
                                    <li class="page-item"><a class="page-link" href="?{% if query %}q={{ query }}&{% endif %}{% if sort_by %}sort={{ sort_by }}&{% endif %}page={{ num }}">{{ num }}</a></li>
                                {% elif forloop.first or forloop.last %}
                                    <li class="page-item"><a class="page-link" href="#">...</a></li>
                                {% endif %}
                            {% endfor %}

                            <!-- Next Button -->
                            <li class="page-item {% if not brands.has_next %}disabled{% endif %}">
                                <a class="page-link" href="{% if brands.has_next %}?{% if query %}q={{ query }}&{% endif %}{% if sort_by %}sort={{ sort_by }}&{% endif %}page={{ brands.next_page_number }}{% else %}#{% endif %}" aria-label="Next">
                                    <span aria-hidden="true">
                                        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <g clip-path="url(#clip0_2880_6407)">
                                                <path d="M9.42017 6.00011C9.42017 6.2151 9.33808 6.43013 9.17427 6.5941L4.01441 11.7538C3.68618 12.0821 3.15402 12.0821 2.82592 11.7538C2.49783 11.4257 2.49783 10.8937 2.82592 10.5654L7.39159 6.00011L2.82624 1.43461C2.49815 1.10652 2.49815 0.574382 2.82624 0.246315C3.15434 -0.0820709 3.68634 -0.0820709 4.01457 0.246315L9.17446 5.40596C9.33824 5.57001 9.42017 5.78505 9.42017 6.00011Z" fill="#050B20"/>
                                            </g>
                                            <defs>
                                                <clipPath id="clip0_2880_6407">
                                                    <rect width="12" height="12" fill="white" transform="translate(12 12) rotate(-180)"/>
                                                </clipPath>
                                            </defs>
                                        </svg>
                                    </span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>

                        <div class="text">
                            Showing results {{ brands.start_index }} - {{ brands.end_index }} of {{ brands.paginator.count }}
                        </div>
                    </nav>
                </div>
            {% endif %}
        </div>
    </section>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const select = document.querySelector(".drop-menu .select");
            const dropdown = document.querySelector(".drop-menu .dropdown");
            const hiddenInput = document.querySelector(".drop-menu input[name='sort']");

            select.addEventListener("click", () => {
                dropdown.style.display = dropdown.style.display === "none" ? "block" : "none";
            });

            dropdown.querySelectorAll("li").forEach(li => {
                li.addEventListener("click", () => {
                    hiddenInput.value = li.dataset.value;
                    select.querySelector("span").innerText = li.innerText;
                    dropdown.style.display = "none";
                    document.querySelector("form").submit();
                });
            });
        });
    </script>

{% endblock %}

templates/pages/contact.html
{% extends 'layouts/app.html' %}

{% block content %}

    <section class="contact-us-section layout-radius">
        <div class="boxcar-container">
            <!-- boxcar-title -->
            <div class="boxcar-title-three wow fadeInUp">
                <ul class="breadcrumb">
                    <li>
                        <a href="{% url 'base:home' %}">Home</a>
                    </li>
                    <li>
                        <span>
                            Contact Us
                        </span>
                    </li>
                </ul>
                <h2>Contact Us</h2>
            </div>
            <!-- End section title -->
            <!-- map-sec -->
            <div class="map-sec">
                <div class="goole-iframe">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3987.5056929438533!2d30.057169075877542!3d-1.9508994367155497!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x19dca42f5b485059%3A0x180264b50c93d84!2sNorrsken%20House%2C%201%20KN%2078%20St%2C%20Kigali!5e0!3m2!1sen!2srw!4v1752317477927!5m2!1sen!2srw"></iframe>
                </div>
            </div>
            <!-- End map-section -->
            <!-- calculater-section -->
            <div class="calculater-sec">
                <div class="right-box">
                    <div class="row">
                        <!-- content-column -->
                        <div class="col-lg-6 content-column">
                            <div class="inner-column">
                                <div class="boxcar-title">
                                    <h2>Get In Touch</h2>
                                    <p>Etiam pharetra egestas interdum blandit viverra morbi consequat mi non bibendum egestas quam egestas nulla.</p>
                                </div>
                                <form class="row" method="POST">
                                    {% csrf_token %}
                                    <div class="col-lg-6">
                                        <div class="form_boxes">
                                            {{ form.first_name.label_tag }}
                                            {{ form.first_name }}
                                            {{ form.first_name.errors }}
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form_boxes">
                                            {{ form.last_name.label_tag }}
                                            {{ form.last_name }}
                                            {{ form.last_name.errors }}
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form_boxes">
                                            {{ form.email.label_tag }}
                                            {{ form.email }}
                                            {{ form.email.errors }}
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form_boxes">
                                            {{ form.phone.label_tag }}
                                            {{ form.phone }}
                                            {{ form.phone.errors }}
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="form_boxes v2">
                                            {{ form.message.label_tag }}
                                            {{ form.message }}
                                            {{ form.message.errors }}
                                        </div>
                                    </div>
                                    <div class="form-submit">
                                        <button type="submit" class="theme-btn">
                                            Send Message
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <!-- contact-column -->
                        <div class="contact-column col-lg-6 col-md-12 col-sm-12">
                            <div class="inner-column">
                                <div class="boxcar-title">
                                    <h6 class="title">Contact details</h6>
                                    <div class="text">
                                        Get in touch with us through the information below. Whether you have questions, need support, or just want to connect, we're here to help and respond promptly to your inquiries.
                                    </div>
                                </div>

                                <div class="content-box">
                                    <h6 class="title">
                                        <span class="icon">
                                            <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M12.9999 4.0625C8.67871 4.0625 5.14575 7.64734 5.14575 12.1068C5.14575 14.3555 6.04517 16.8458 7.5169 18.7689C8.99243 20.697 10.9454 21.9375 12.9999 21.9375C15.0545 21.9375 17.0074 20.697 18.483 18.7689C19.9547 16.8458 20.8541 14.3555 20.8541 12.1068C20.8541 7.64734 17.3211 4.0625 12.9999 4.0625ZM3.52075 12.1068C3.52075 6.78329 7.74819 2.4375 12.9999 2.4375C18.2516 2.4375 22.4791 6.78329 22.4791 12.1068C22.4791 14.7496 21.4384 17.5809 19.7735 19.7564C18.1123 21.9271 15.7319 23.5625 12.9999 23.5625C10.268 23.5625 7.8876 21.9271 6.22642 19.7564C4.56143 17.5809 3.52075 14.7496 3.52075 12.1068Z" fill="#050B20"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M9.479 11.375C9.479 9.4305 11.0554 7.85417 12.9998 7.85417C14.9443 7.85417 16.5207 9.4305 16.5207 11.375C16.5207 13.3195 14.9443 14.8958 12.9998 14.8958C11.0554 14.8958 9.479 13.3195 9.479 11.375ZM12.9998 9.47917C11.9528 9.47917 11.104 10.328 11.104 11.375C11.104 12.422 11.9528 13.2708 12.9998 13.2708C14.0469 13.2708 14.8957 12.422 14.8957 11.375C14.8957 10.328 14.0469 9.47917 12.9998 9.47917Z" fill="#E1E1E1"/>
                                            </svg>
                                        </span>
                                        Address
                                    </h6>
                                    <div class="text">
                                        {{ settings.address|default:'Norrsken House Kigali 1 KN 78 St, Kigali' }}
                                    </div>
                                </div>
                                <div class="content-box">
                                    <h6 class="title">
                                        <span class="icon">
                                            <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M12.7584 14.5869C12.0336 14.5869 11.3111 14.3474 10.7065 13.8686L5.84779 9.95128C5.49787 9.66962 5.44371 9.1572 5.72429 8.80837C6.00704 8.46062 6.51837 8.40537 6.86721 8.68595L11.7216 12.5989C12.3316 13.0821 13.1906 13.0821 13.8049 12.5946L18.6106 8.68812C18.9594 8.4032 19.4707 8.45737 19.7546 8.8062C20.0373 9.15395 19.9842 9.66528 19.6365 9.94912L14.8221 13.8621C14.2133 14.3453 13.4853 14.5869 12.7584 14.5869Z" fill="#E1E1E1"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M18.0472 21.6667C18.0493 21.6645 18.058 21.6667 18.0645 21.6667C19.3006 21.6667 20.3969 21.2247 21.2376 20.3851C22.2137 19.4133 22.7499 18.0169 22.7499 16.4537V9.01333C22.7499 5.98758 20.7718 3.79166 18.0472 3.79166H7.411C4.68642 3.79166 2.70825 5.98758 2.70825 9.01333V16.4537C2.70825 18.0169 3.24558 19.4133 4.22058 20.3851C5.06125 21.2247 6.15867 21.6667 7.39367 21.6667H18.0472ZM7.39042 23.2917C5.71883 23.2917 4.226 22.685 3.07334 21.5367C1.78959 20.2562 1.08325 18.4513 1.08325 16.4537V9.01333C1.08325 5.11008 3.8035 2.16666 7.411 2.16666H18.0472C21.6547 2.16666 24.3749 5.11008 24.3749 9.01333V16.4537C24.3749 18.4513 23.6686 20.2562 22.3848 21.5367C21.2333 22.6839 19.7393 23.2917 18.0645 23.2917H7.39042Z" fill="#050B20"/>
                                            </svg>
                                        </span>
                                        Email
                                    </h6>
                                    <div class="text">{{ settings.email|default:'plutobooking@gmail.com' }}</div>
                                </div>
                                <div class="content-box">
                                    <h6 class="title">
                                        <span class="icon">
                                            <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M23.5126 10.9886C23.1042 10.9886 22.7532 10.682 22.7066 10.2671C22.2949 6.60979 19.4533 3.77145 15.796 3.3652C15.3507 3.31537 15.029 2.91454 15.0788 2.4682C15.1276 2.02295 15.5273 1.69037 15.9758 1.75103C20.3926 2.2407 23.8246 5.66837 24.3207 10.0851C24.3717 10.5315 24.0499 10.9333 23.6047 10.9832C23.5743 10.9864 23.5429 10.9886 23.5126 10.9886Z" fill="#E1E1E1"/>
                                                <path d="M19.676 11.0003C19.2947 11.0003 18.9556 10.7316 18.8798 10.3438C18.5678 8.74044 17.3317 7.50436 15.7305 7.19344C15.2896 7.10786 15.0025 6.68211 15.0881 6.24119C15.1737 5.80027 15.6103 5.51319 16.0403 5.59877C18.2948 6.03644 20.0357 7.77628 20.4744 10.0318C20.56 10.4738 20.2729 10.8995 19.8331 10.9851C19.78 10.9949 19.728 11.0003 19.676 11.0003Z" fill="#E1E1E1"/>
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8.10554 17.8102C13.2113 22.9171 16.6108 24.2561 18.758 24.2561C19.8175 24.2561 20.5737 23.93 21.0774 23.5681C21.1002 23.5551 23.4315 22.1295 23.8399 19.9715C24.0328 18.9586 23.7511 17.9565 23.0274 17.0725C20.0461 13.4531 18.5273 13.7911 16.8503 14.6068C15.82 15.1116 15.0064 15.5038 12.7087 13.2082C10.4122 10.9108 10.8084 10.0971 11.3099 9.06703C12.1267 7.39003 12.4628 5.87083 8.84221 2.88733C7.96038 2.16692 6.96479 1.88525 5.95296 2.07483C3.82638 2.47242 2.39421 4.76583 2.39421 4.76583C1.25454 6.36592 0.481047 10.1868 8.10554 17.8102ZM6.28446 3.66517C6.37979 3.65 6.47404 3.64133 6.56721 3.64133C6.99188 3.64133 7.40138 3.80708 7.80979 4.14292C10.7294 6.54789 10.36 7.30624 9.84864 8.35598C9.08055 9.93439 8.67863 11.4749 11.5593 14.3576C14.4431 17.2404 15.9847 16.8385 17.5609 16.0682L17.5635 16.0669C18.612 15.5573 19.37 15.1889 21.7718 18.1049C22.1824 18.6054 22.3395 19.1059 22.2507 19.6335C22.0459 20.8468 20.6354 21.9334 20.2086 22.1977C18.68 23.2876 14.9999 22.4068 9.25388 16.6619C3.51004 10.917 2.62821 7.23692 3.75704 5.64983C3.98238 5.28258 5.07329 3.86992 6.28446 3.66517Z" fill="#050B20"/>
                                            </svg>
                                        </span>
                                        Phone
                                    </h6>
                                    <div class="text">{{ settings.phone_number|default:'250 780 084 902' }}</div>
                                </div>
                                <div class="social-icons">
                                    <h6 class="title">Follow us</h6>
                                    <ul class="social-links">
                                        <li>
                                            <a href="#">
                                                <i class="fa-brands fa-facebook-f"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa-brands fa-twitter"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa-brands fa-instagram"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <i class="fa-brands fa-linkedin-in"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/pages/how-it-works.html
{% extends 'layouts/main.html' %}

{% block content %}

    How It Work

{% endblock content %}

templates/pages/privacy-policy.html
{% extends 'layouts/app.html' %}

{% block content %}

    <section class="contact-us-section layout-radius">
        <div class="boxcar-container">
            <!-- boxcar-title -->
            <div class="boxcar-title-three wow fadeInUp">
                <ul class="breadcrumb">
                    <li>
                        <a href="{% url 'base:home' %}">Home</a>
                    </li>
                    <li>
                        <span>
                            Privacy Policy
                        </span>
                    </li>
                </ul>
                <h2>Privacy Policy</h2>
            </div>
        </div>
    </section>

{% endblock content %}