base/urls.py
from base.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    path('', home, name="home"),
    path('brands/', brands, name="brands"),
    path('how-it-works/', howItWorks, name="howItWorks"),
    path('privacy-policy/', privacyPolicy, name="privacyPolicy"),
    path('contact-us/', contact, name="contact"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car/urls.py
from car.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'car'

urlpatterns = [
    path('', getCars, name="getCars"),
    path('car/<int:id>/', carDetails, name="carDetails"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from hotel.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'hotel'

urlpatterns = [
    path('', getHotels, name="getHotels"),
    path('hotel/<int:hotel_id>/rooms/', hotelRooms, name="hotelRooms"),
    path('hotel/<int:hotel_id>/room/<int:room_id>/', roomDetails, name="roomDetails"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plane/urls.py
from plane.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'plane'

urlpatterns = [
    path('', getPlanes, name="getPlanes"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pluto/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
    path('cars/', include('car.urls')),
    path('users/', include('user.urls')),
    path('auth/', include('account.urls')),
    path('hotels/', include('hotel.urls')),
    path('planes/', include('plane.urls')),
    path('payment/', include('payment.urls')),
]

# Serve static and media files manually if DEBUG is False
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    from django.views.static import serve
    from django.urls import re_path

    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
        re_path(r'^static/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

handler404 = 'base.views.custom_404_view'

user/urls.py
from user.views import *
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static

app_name = 'user'

urlpatterns = [
    path('dashboard/', dashboard, name="dashboard"),
    path('room-booking/', roomBooking, name="roomBooking"),
    path('car-booking/', carBooking, name="carBooking"),
    path('plane-booking/', planeBooking, name="planeBooking"),
    path('profile/', profile, name="profile"),
    path('change-password/', changePassword, name="changePassword"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
{% load static %}

<footer class="boxcar-footer footer-style-one v1 cus-st-1">
    <div class="footer-top">
        <div class="boxcar-container">
            <div class="right-box">
                <div class="top-left wow fadeInUp">
                    <h6 class="title">
                        Quick Booking
                    </h6>
                    <div class="text">
                        Receive pricing updates, shopping tips & more!
                    </div>
                </div>
                <div class="subscribe-form wow fadeInUp" data-wow-delay="100ms">
                    <form method="post" action="#">
                        <div class="form-group">
                            <input type="email" name="email" class="email" value="" placeholder="Your e-mail address" required="">
                            <button type="button" class="theme-btn btn-style-one hover-light">
                                <span class="btn-title">Sign Up</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="widgets-section">
        <div class="boxcar-container">
            <div class="row">
                <!-- Footer COlumn -->
                <div class="footer-column-two col-lg-9 col-md-6 col-sm-12">
                    <div class="row">
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="footer-widget links-widget wow fadeInUp">
                                <h4 class="widget-title">Useful Links</h4>
                                <div class="widget-content">
                                    <ul class="user-links style-two">
                                        <li>
                                            <a href="{% url 'base:howItWorks' %}">How It Works</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'base:contact' %}">Contact Us</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="footer-widget links-widget wow fadeInUp" data-wow-delay="100ms">
                                <h4 class="widget-title">Hotels</h4>
                                <div class="widget-content">
                                    <ul class="user-links style-two">
                                        <li>
                                            <a href="#">
                                                5 Star
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="footer-widget links-widget wow fadeInUp" data-wow-delay="200ms">
                                <h4 class="widget-title">Cars</h4>
                                <div class="widget-content">
                                    <ul class="user-links style-two">
                                        <li>
                                            <a href="#">Toyota</a>
                                        </li>
                                        <li>
                                            <a href="#">Audi</a>
                                        </li>
                                        <li>
                                            <a href="#">Kia</a>
                                        </li>
                                        <li>
                                            <a href="#">BMW</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-6 col-sm-12">
                            <div class="footer-widget links-widget wow fadeInUp" data-wow-delay="300ms">
                                <h4 class="widget-title">Plane Booking</h4>
                                <div class="widget-content">
                                    <ul class="user-links style-two">
                                        <li>
                                            <a href="#">Book a Plane</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- footer column -->
                <div class="footer-column col-lg-3 col-md-6 col-sm-12">
                    <div class="footer-widget social-widget wow fadeInUp" data-wow-delay="400ms">
                        <h4 class="widget-title">
                            Download App
                        </h4>
                        <div class="widget-content">
                            <a href="#" class="store">
                                <img src="{% static 'images/icons/apple.png' %}">
                                <span>Download on the</span>
                                <h6 class="title">Apple Store</h6>
                            </a>
                            <a href="#" class="store two">
                                <img src="{% static 'images/icons/play.png' %}">
                                <span>Get in on</span>
                                <h6 class="title">Google Play</h6>
                            </a>
                            <div class="social-icons">
                                <h6 class="title">Connect With Us</h6>
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-facebook-f"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-instagram"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-linkedin-in"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--  Footer Bottom -->
    <div class="footer-bottom">
        <div class="boxcar-container">
            <div class="inner-container">
                <div class="copyright-text wow fadeInUp">
                    © {% now "Y" %} Pluto Booking. All rights reserved. Developed by <a href="https://www.nexcodes.dev/" target="_blank">NE<span style="color: red; font-weight: bold;">X</span>CODE</a>
                </div>
                <ul class="footer-nav wow fadeInUp" data-wow-delay="100ms">
                    <li>
                        <a href="#">Terms & Conditions</a>
                    </li>
                    <li>
                        <a href="#">Privacy Notice</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/components/header-main.html
{% load static %}

<header class="boxcar-header header-style-v1 header-default">
    <div class="header-inner">
        <div class="inner-container">
            <!-- Main box -->
            <div class="c-box">
                <div class="logo-inner">
                    <div class="logo">
                        <a href="{% url 'base:home' %}">
                            <img src="{% static 'images/logo-w.png' %}" alt="" title="Pluto Booking">
                        </a>
                    </div>
                </div>
                <!--Nav Box-->
                <div class="nav-out-bar">
                    <nav class="nav main-menu">
                        <ul class="navigation" id="navbar">
                            {% comment %} <li>
                                <a href="{% url 'base:home' %}">Home</a>
                            </li> {% endcomment %}
                            <li>
                                <a href="{% url 'hotel:getHotels' %}">Hotels</a>
                            </li>
                            <li>
                                <a href="{% url 'car:getCars' %}">Cars</a>
                            </li>
                            <li>
                                <a href="{% url 'plane:getPlanes' %}">Plane Booking</a>
                            </li>
                            <li>
                                <a href="{% url 'base:contact' %}">Contact Us</a>
                            </li>
                        </ul>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <div class="right-box">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'auth:getLogout' %}" title="" class="box-account">
                            <div class="icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
                                    <defs>
                                        <mask id="letsIconsSignOutCircleDuotoneLine0">
                                            <g fill="none">
                                                <circle cx="6" cy="6" r="6" fill="#fff" fill-opacity="0.25" transform="matrix(0 -1 -1 0 20 18)" />
                                                <path stroke="#c0c0c0" stroke-opacity="0.25" stroke-width="0.6" d="M7.7 12a6.3 6.3 0 1 1 12.6 0a6.3 6.3 0 0 1-12.6 0Z" />
                                                <path stroke="#fff" stroke-width="1.2" d="M8 18.928A8 8 0 1 0 8 5.072" />
                                                <path fill="#fff" d="m2 12l-.469-.375l-.3.375l.3.375zm9 .6a.6.6 0 1 0 0-1.2zM5.531 6.625l-4 5l.938.75l4-5zm-4 5.75l4 5l.938-.75l-4-5zM2 12.6h9v-1.2H2z" />
                                            </g>
                                        </mask>
                                    </defs>
                                    <path fill="currentColor" d="M0 0h24v24H0z" mask="url(#letsIconsSignOutCircleDuotoneLine0)" />
                                </svg>
                            </div>
                            Sign Out
                        </a>
                        <div class="btn">
                            <a href="{% url 'user:dashboard' %}" class="header-btn-two btn-anim">
                                Dashboard
                            </a>
                        </div>
                    {% else %}
                        <a href="{% url 'auth:getLogin' %}" title="" class="box-account">
                            <div class="icon">
                                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0_147_6490)">
                                        <path d="M7.99998 9.01221C3.19258 9.01221 0.544983 11.2865 0.544983 15.4161C0.544983 15.7386 0.806389 16.0001 1.12892 16.0001H14.871C15.1935 16.0001 15.455 15.7386 15.455 15.4161C15.455 11.2867 12.8074 9.01221 7.99998 9.01221ZM1.73411 14.8322C1.9638 11.7445 4.06889 10.1801 7.99998 10.1801C11.9311 10.1801 14.0362 11.7445 14.2661 14.8322H1.73411Z" fill="white"/>
                                        <path d="M7.99999 0C5.79171 0 4.12653 1.69869 4.12653 3.95116C4.12653 6.26959 5.86415 8.15553 7.99999 8.15553C10.1358 8.15553 11.8735 6.26959 11.8735 3.95134C11.8735 1.69869 10.2083 0 7.99999 0ZM7.99999 6.98784C6.50803 6.98784 5.2944 5.62569 5.2944 3.95134C5.2944 2.3385 6.43231 1.16788 7.99999 1.16788C9.54259 1.16788 10.7056 2.36438 10.7056 3.95134C10.7056 5.62569 9.49196 6.98784 7.99999 6.98784Z" fill="white"/>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_147_6490">
                                            <rect width="16" height="16" fill="white"/>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </div>
                            Sign In
                        </a>
                        <div class="btn">
                            <a href="{% url 'auth:getRegister' %}" class="header-btn-two btn-anim">
                                Sign Up
                            </a>
                        </div>
                    {% endif %}
                    <div class="mobile-navigation">
                        <a href="#nav-mobile" title="">
                            <!-- <i class="fa fa-bars"></i> -->
                            <svg width="22" height="11" viewBox="0 0 22 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <rect width="22" height="2" fill="white"/>
                                <rect y="9" width="22" height="2" fill="white"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Mobile Menu  -->
        </div>
    </div>
    <!-- Header Search -->
    <div class="search-popup">
        <span class="search-back-drop"></span>
        <button class="close-search">
            <span class="fa fa-times"></span>
        </button>
    </div>
    <!-- End Header Search -->
    <div id="nav-mobile"></div>
</header>

templates/components/header.html
{% load static %}

<header class="boxcar-header header-style-v1 style-two inner-header cus-style-1">
    <div class="header-inner">
        <div class="inner-container">
            <!-- Main box -->
            <div class="c-box">
                <div class="logo-inner">
                    <div class="logo">
                        <a href="{% url 'base:home' %}">
                            <img src="{% static 'images/logo-w.png' %}" alt="" title="Pluto Booking">
                        </a>
                    </div>
                </div>
                <!--Nav Box-->
                <div class="nav-out-bar">
                    <nav class="nav main-menu">
                        <ul class="navigation" id="navbar">
                            {% comment %} <li>
                                <a href="{% url 'base:home' %}">Home</a>
                            </li> {% endcomment %}
                            <li>
                                <a href="{% url 'hotel:getHotels' %}">Hotels</a>
                            </li>
                            <li>
                                <a href="{% url 'car:getCars' %}">Cars</a>
                            </li>
                            <li>
                                <a href="{% url 'plane:getPlanes' %}">Plane Booking</a>
                            </li>
                            <li>
                                <a href="{% url 'base:contact' %}">Contact Us</a>
                            </li>
                        </ul>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <div class="right-box">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'auth:getLogout' %}" title="" class="box-account">
                            <div class="icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24">
                                    <defs>
                                        <mask id="letsIconsSignOutCircleDuotoneLine0">
                                            <g fill="none">
                                                <circle cx="6" cy="6" r="6" fill="#fff" fill-opacity="0.25" transform="matrix(0 -1 -1 0 20 18)" />
                                                <path stroke="#c0c0c0" stroke-opacity="0.25" stroke-width="0.6" d="M7.7 12a6.3 6.3 0 1 1 12.6 0a6.3 6.3 0 0 1-12.6 0Z" />
                                                <path stroke="#fff" stroke-width="1.2" d="M8 18.928A8 8 0 1 0 8 5.072" />
                                                <path fill="#fff" d="m2 12l-.469-.375l-.3.375l.3.375zm9 .6a.6.6 0 1 0 0-1.2zM5.531 6.625l-4 5l.938.75l4-5zm-4 5.75l4 5l.938-.75l-4-5zM2 12.6h9v-1.2H2z" />
                                            </g>
                                        </mask>
                                    </defs>
                                    <path fill="currentColor" d="M0 0h24v24H0z" mask="url(#letsIconsSignOutCircleDuotoneLine0)" />
                                </svg>
                            </div>
                            Sign Out
                        </a>
                        <div class="btn">
                            <a href="{% url 'user:dashboard' %}" class="header-btn-two btn-anim" style="display: flex; justify-content: space-between;">
                                <div class="icon" style="padding-right: 10px;">
                                    <svg width="12" height="12" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <g clip-path="url(#clip0_147_6490)">
                                            <path d="M7.99998 9.01221C3.19258 9.01221 0.544983 11.2865 0.544983 15.4161C0.544983 15.7386 0.806389 16.0001 1.12892 16.0001H14.871C15.1935 16.0001 15.455 15.7386 15.455 15.4161C15.455 11.2867 12.8074 9.01221 7.99998 9.01221ZM1.73411 14.8322C1.9638 11.7445 4.06889 10.1801 7.99998 10.1801C11.9311 10.1801 14.0362 11.7445 14.2661 14.8322H1.73411Z" fill="white"/>
                                            <path d="M7.99999 0C5.79171 0 4.12653 1.69869 4.12653 3.95116C4.12653 6.26959 5.86415 8.15553 7.99999 8.15553C10.1358 8.15553 11.8735 6.26959 11.8735 3.95134C11.8735 1.69869 10.2083 0 7.99999 0ZM7.99999 6.98784C6.50803 6.98784 5.2944 5.62569 5.2944 3.95134C5.2944 2.3385 6.43231 1.16788 7.99999 1.16788C9.54259 1.16788 10.7056 2.36438 10.7056 3.95134C10.7056 5.62569 9.49196 6.98784 7.99999 6.98784Z" fill="white"/>
                                        </g>
                                        <defs>
                                            <clipPath id="clip0_147_6490">
                                                <rect width="16" height="16" fill="white"/>
                                            </clipPath>
                                        </defs>
                                    </svg>
                                </div>
                                Dashboard
                            </a>
                        </div>
                    {% else %}
                        <a href="{% url 'auth:getLogin' %}" title="" class="box-account">
                            <div class="icon">
                                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <g clip-path="url(#clip0_147_6490)">
                                        <path d="M7.99998 9.01221C3.19258 9.01221 0.544983 11.2865 0.544983 15.4161C0.544983 15.7386 0.806389 16.0001 1.12892 16.0001H14.871C15.1935 16.0001 15.455 15.7386 15.455 15.4161C15.455 11.2867 12.8074 9.01221 7.99998 9.01221ZM1.73411 14.8322C1.9638 11.7445 4.06889 10.1801 7.99998 10.1801C11.9311 10.1801 14.0362 11.7445 14.2661 14.8322H1.73411Z" fill="white"/>
                                        <path d="M7.99999 0C5.79171 0 4.12653 1.69869 4.12653 3.95116C4.12653 6.26959 5.86415 8.15553 7.99999 8.15553C10.1358 8.15553 11.8735 6.26959 11.8735 3.95134C11.8735 1.69869 10.2083 0 7.99999 0ZM7.99999 6.98784C6.50803 6.98784 5.2944 5.62569 5.2944 3.95134C5.2944 2.3385 6.43231 1.16788 7.99999 1.16788C9.54259 1.16788 10.7056 2.36438 10.7056 3.95134C10.7056 5.62569 9.49196 6.98784 7.99999 6.98784Z" fill="white"/>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_147_6490">
                                            <rect width="16" height="16" fill="white"/>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </div>
                            Sign In
                        </a>
                        <div class="btn">
                            <a href="{% url 'auth:getRegister' %}" class="header-btn-two btn-anim">
                                Sign Up
                            </a>
                        </div>
                    {% endif %}
                    <div class="mobile-navigation">
                        <a href="#nav-mobile" title="">
                            <svg width="22" height="11" viewBox="0 0 22 11" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <rect width="22" height="2" fill="white"/>
                                <rect y="9" width="22" height="2" fill="white"/>
                            </svg>
                        </a>
                    </div>
                </div>
            </div>
            <!-- Mobile Menu  -->
        </div>
    </div>
    <!-- Header Search -->
    <div class="search-popup">
        <span class="search-back-drop"></span>
        <button class="close-search">
            <span class="fa fa-times"></span>
        </button>
    </div>
    <!-- End Header Search -->
    <div id="nav-mobile"></div>
</header>